# . docker-compose.yml
version: '3.9'

services:
  ##############################################
  ## mysql 8
  ##############################################
  db :
    #platform: linux/x86_64
    image: library/mysql:8.0.36 #Mysql 버전입니다.
    container_name: dragon_mysql #닉네임 설정입니다.
    restart: always
    command:  #옵션을 줄 수 있어요.
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root #DB 관리자 접속 비밀번호입니다.
      TZ: Asia/Seoul  #시간 기준 표시입니다.
    ports:
      - 11802:3306  #같은 포트는 충돌이 생겨요.
    volumes:
      # 디렉토리 마운트 설정
      #- ~/programs/docker/mysql8/data:/var/lib/mysql #맥 입니다.
      - ./docker/db/data:/var/lib/mysql #윈도우 입니다.